STUDENTS_IDX_SETTINGS = {
    "minWordSizefor1Typo": 4,
    "minWordSizefor2Typos": 8,
    "hitsPerPage": 20,
    "maxValuesPerFacet": 100,
    "searchableAttributes": [
        "title",
        "name_formats.preferred_short_name",
        "unordered(name_formats.full_name)",
        "unordered(name_formats.preferred_long_name)",
        "unordered(name_formats.name_with_initials)",
        "unordered(current_affiliation)",
        "unordered(content)",
        "unordered(metadata.emails.personal)",
        "unordered(metadata.emails.university)",
        "unordered(location)",
        "unordered(interests)",
    ],
    "numericAttributesToIndex": None,
    "attributesToRetrieve": None,
    "unretrievableAttributes": None,
    "optionalWords": None,
    "attributesForFaceting": [
        "searchable(interests)",
        "batch",
        "searchable(current_affiliation)",
        "type",
    ],
    "attributesToSnippet": ["snippet:20", "content:10"],
    "attributesToHighlight": None,
    "paginationLimitedTo": 100,
    "attributeForDistinct": "chunk",
    "exactOnSingleWordQuery": "attribute",
    "disableTypoToleranceOnAttributes": [
        "name_formats.full_name",
        "name_formats.preferred_short_name",
    ],
    "ranking": [
        "typo",
        "geo",
        "words",
        "filters",
        "proximity",
        "attribute",
        "exact",
        "custom",
    ],
    "customRanking": ["desc(batch)"],
    "separatorsToIndex": "",
    "removeWordsIfNoResults": "none",
    "queryType": "prefixLast",
    "highlightPreTag": "<em>",
    "highlightPostTag": "</em>",
    "alternativesAsExact": ["ignorePlurals", "singleWordSynonym"],
    "renderingContent": {
        "facetOrdering": {
            "facets": {"order": ["batch", "current_affiliation"]},
            "values": {
                "batch": {"sortRemainingBy": "count"},
                "current_affiliation": {"sortRemainingBy": "count"},
            },
        }
    },
}
