name: Weekly Updates

on:
  schedule:
    # At 19:00 on Sunday. (12.30 mid night in Sri Lanka)
    - cron: "0 19 * * 0"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  update_weekly:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Performance Badges for the students
        run: |
          cd ./python_scripts
          python3 update_badges.py
          cd ../

      - name: Update ACES Committee Details
        run: |
          cd ./python_scripts
          python3 update_societies.py
          cd ../

      - name: Commit and push the changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Weekly workflow" || echo "No changes"
          git push
